version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HEADLESS=true
    env_file:
      - .env
    volumes:
      - ./whatsapp-session:/app/whatsapp-session
      - ./logs:/app/logs
    command: ["npm", "start"]
    networks:
      - whatsapp-network
    depends_on:
      - slack-server

  slack-server:
    build: .
    container_name: slack-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./whatsapp-session:/app/whatsapp-session
      - ./logs:/app/logs
    command: ["npm", "run", "server"]
    networks:
      - whatsapp-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - slack-server
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp_session:
  app_logs: